# apiVersion: v1
# data:
#   prometheus.yml: |-
#     global:
#       scrape_interval: 15s 
#       evaluation_interval: 15s 
#     scrape_configs:
#       - job_name: "exporter"
#         static_configs:
#           - targets: ["exporter-prometheus-mongodb-exporter:9216"]
# kind: ConfigMap
# metadata:
#   name: prometheus
#   namespace: prometheus
