apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless
  namespace: prometheus
spec:
  selector:
    app: prometheus
  clusterIP: None
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090